import type { Metadata } from "next";
import Head from 'next/head';
import { motion } from "motion/react"
import { ToastContainer } from 'react-toastify';
import Provider from "./Provider";
import Header from "@/components/Header";
import "./globals.css";

export const metadata: Metadata = {
  title: "Next App",
  description: "Generated by create next app",
};
declare global {
  interface Window {
    ethereum: any;
    okxwallet: any;
    coinbaseWalletExtension: any;
    phantom: {
      solana: any
    }
  }
}
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Provider >
          <div className=" min-h-screen flex flex-col">
            <div className="fiexed inset-0 overflow-hidden pointer-events-none">
              <div className=" absolute inset-0 bg-linear-to-br from-gray-900 via-gray-800 to-gray-900"></div>
              <div className="absolute inset-0 tech-grid" />
              <div className="absolute top-0 left-0 w-full h-full bg-[radial-gradient(circle_at_center,var(--tw-gradient-stops))] from-primary-500/10 via-transparent to-transparent" />
            </div>
            <div className=" relative flex flex-col grow">
              <ToastContainer
                position="top-right"
                autoClose={3000}
                hideProgressBar={false}
                newestOnTop={false}
                closeOnClick
                rtl={false}
                pauseOnFocusLoss
                draggable
                pauseOnHover
                theme="light"
                toastClassName="custom-toast"
                progressClassName="custom-toast-progress"
              />
              <Header />
              {children}
            </div>
            
          </div>
        </Provider>
      </body>
    </html>
  );
}
